/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Card {

    public enum Rank {
        ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING
    }

    public enum Suit{
        SPADES, HEARTS, DIAMONDS, CLUBS
    }
    private final Rank rank; 
    private final Suit suit; 

    public Card(Rank rank, Suit suit){
        if(rank == null||suit == null){
            throw new IllegalArgumentException("Rank and Suit cannot be null");
        }
        this.rank = rank;
        this.suit = suit;
    }

    public int getRank(){
        return rank;
    }

    public int getSuit(){
        return suit;
    }

    public String toString(){
        return rank + "of" + suit;
    }






    public static void main(String[] args) {
        System.out.println(new Card().getGreeting());
    }
}
